---
abstract: 'Extract variable names from interpolated strings.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Test::Deep: '0'
  Test::FailWarnings: '0'
  Test::More: '0.94'
configure_requires:
  Module::Build: '0'
dynamic_config: 1
generated_by: 'Module::Build version 0.4205, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: String-InterpolatedVariables
provides:
  String::InterpolatedVariables:
    file: lib/String/InterpolatedVariables.pm
    version: v1.1.0
requires:
  Readonly: '0'
  perl: '5.006'
resources:
  bugtracker: https://github.com/guillaumeaubert/String-InterpolatedVariables/issues
  homepage: https://metacpan.org/release/String-InterpolatedVariables
  license: http://dev.perl.org/licenses/
  repository: https://github.com/guillaumeaubert/String-InterpolatedVariables
version: v1.1.0
