---
abstract: 'Extract variable names from interpolated strings.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Test::FailWarnings: 0
  Test::More: 0.94
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4007, CPAN::Meta::Converter version 2.132830'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: String-InterpolatedVariables
provides:
  String::InterpolatedVariables:
    file: lib/String/InterpolatedVariables.pm
    version: v1.0.1
requires:
  Readonly: 0
  perl: 5.006
resources:
  bugtracker: https://github.com/guillaumeaubert/String-InterpolatedVariables/issues
  homepage: https://metacpan.org/release/String-InterpolatedVariables
  license: http://www.gnu.org/licenses/gpl-3.0.txt
  repository: https://github.com/guillaumeaubert/String-InterpolatedVariables
version: v1.0.1
